[book]
title = "Skripta OSE-SYS"
authors = ["František Hrubý", "Samuel Šidlichovský"]
language = "cs"

[output.html]
mathjax-support = true
smart-punctuation = true
definition-lists = true
admonitions = true